# vi: ft=i3config

font Comic Shanns 11

set $black #000000
set $grey #151515

set $bg-pri #c0c0c0
set $bg-focus #000181
set $bg-unfoc #808080
set $bg-alert #008081
set $fg-unfoc #c9c9c9
set $fg-dark #000000
set $fg-bri #ffffff

#                        border    background  text      indicator
client.focused           $bg-pri   $bg-focus   $fg-bri   $black     $bg-pri
client.unfocused         $bg-pri   $bg-unfoc   $fg-unfoc $black     $bg-pri
client.focused_inactive  $bg-pri   $bg-unfoc   $fg-unfoc $black     $bg-pri
client.urgent            $bg-alert $bg-focus   $fg       $black     $bg-pri
client.placeholder       $bg       $bg         $bg       $bg        $bg-pri
client.background $bg-pri

default_border normal 3
