# vi: ft=i3config

set $sc_center    "AOC Q32G1WG4 0x00000C5F"
set $sc_left      "Dell Inc. DELL U2312HM RJWPW28OAAZL"
set $sc_right_top "Samsung Electric Company C27F390 H4ZM907727"
set $sc_right_bot "Dell Inc. DELL U2312HM 59DJP1AVAXGL"
set $sc_beamer    "SANTAK CORP. S2-TEK TV SN-000000001"

output $sc_center    pos 1080 720  res 2560x1440@144Hz
output $sc_left      pos 0    550  res 1920x1080 transform 270
output $sc_right_top pos 3640 0    res 1920x1080
output $sc_right_bot pos 3640 1080 res 1920x1080
output $beamer       pos 5560 1080 res 1920x1080

workspace 1 output $sc_center
workspace 2 output $sc_left
workspace 3 output $sc_right_top
workspace 4 output $sc_right_bot

workspace 5 output $sc_center
workspace 6 output $sc_left
workspace 7 output $sc_right_top
workspace 8 output $sc_right_bot

workspace 9 output $sc_center
workspace 10 output $sc_left
workspace 11 output $sc_right_top
workspace 12 output $sc_right_bot

workspace 13 output $sc_center
workspace 14 output $sc_left
workspace 15 output $sc_right_top
workspace 16 output $sc_right_bot

workspace 17 output $sc_center
workspace 18 output $sc_left
workspace 19 output $sc_right_top
workspace 20 output $sc_right_bot

focus output $sc_center
