# vi: ft=i3config

set $laptop eDP-1
bindswitch --reload --locked lid:on output $laptop disable
bindswitch --reload --locked lid:off output $laptop enable

output $laptop pos 0 0 res 1920x1080

set $uni_main "Fujitsu Siemens Computers GmbH P27-9 TE QHD YVHU003741"
set $uni_sec "Fujitsu Siemens Computers GmbH P24W-7 LED YV8S213333"
output $uni_main pos 3840 0 res 2560x1440
output $uni_sec pos 1920 0 res 1920x1200
