# vi: ft=swayconfig

# NOTE list outputs with:
#	swaymsg -t get_outputs

set $laptop eDP-1
bindswitch --reload --locked lid:on output $laptop disable
bindswitch --reload --locked lid:off output $laptop enable

output $laptop pos 0 0 res 1920x1080

set $uni_main "Fujitsu Siemens Computers GmbH P27-9 TE QHD YVHU003741"
set $uni_sec "Fujitsu Siemens Computers GmbH P24W-7 LED YV8S213333"
output $uni_main pos 3840 0 res 2560x1440
output $uni_sec pos 1920 0 res 1920x1200
workspace 1 output $uni_main
workspace 2 output $uni_sec

set $home_main "AOC Q32G1WG4 0x00000C5F"
set $home_sec "Dell Inc. DELL U2312HM 59DJP1AVAXGL"
output $home_main pos 3840 0 res 2560x1440
output $home_sec pos 1920 0 res 1920x1200
workspace 1 output $home_main
workspace 2 output $home_sec
