#!/bin/bash

. $HOME/.files

#Screen background feh
shopt -s nullglob

pics=($DOTFILEBASE/pictures/b_*)
#echo $pics
len=${#pics[*]}
ran=$(($RANDOM % len))


echo  ${pics[$ran]}
killall swaybg
swaybg -m fill -i ${pics[$ran]} &
